import io
import datetime

try:
    from reportlab.lib.pagesizes import letter
    from reportlab.pdfgen import canvas
    from reportlab.lib import colors
    HAS_REPORTLAB = True
except ModuleNotFoundError:
    HAS_REPORTLAB = False

def generate_pdf_report(scan_id: str, result: dict) -> bytes:
    """
    Generates a PDF clinical report from an OCT scan result.
    Returns the PDF file as bytes.
    """
    if not HAS_REPORTLAB:
        raise RuntimeError("reportlab package is required for PDF report generation. Please install reportlab.")
    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=letter)
    width, height = letter
    
    # Header
    c.setFont("Helvetica-Bold", 16)
    c.drawString(50, height - 50, "OCT Analysis Clinical Report")
    
    c.setFont("Helvetica", 10)
    c.drawString(50, height - 70, f"Scan ID: {scan_id}")
    c.drawString(50, height - 85, f"Date: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    
    # Content
    diagnosis = result.get("diagnosis", "Unknown")
    confidence = result.get("confidence", 0.0)
    
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, height - 120, "Summary")
    
    c.setFont("Helvetica", 12)
    c.drawString(50, height - 145, f"Primary Diagnosis: {diagnosis}")
    c.drawString(50, height - 165, f"Confidence Score: {confidence:.2%}")
    
    # Detailed Levels
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, height - 210, "Hierarchical Breakdown")
    
    c.setFont("Helvetica", 11)
    y = height - 235
    for level in ["level1", "level2", "level3"]:
        level_data = result.get(level, {})
        pred = level_data.get("prediction", "N/A")
        conf = level_data.get("confidence", 0.0)
        c.drawString(50, y, f"{level.capitalize()}: {pred} ({conf:.2%})")
        y -= 20
        
    # Footer
    c.setFont("Helvetica-Oblique", 9)
    c.setFillColor(colors.gray)
    c.drawString(50, 50, "Generated by Local OCT Analyzer MVP. Not for diagnostic use without clinical review.")
    
    c.save()
    buffer.seek(0)
    return buffer.read()
